[project]
name = "100-days-of-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "colorgram-py>=1.2.0",
    "dotenv>=0.9.9",
    "flask>=3.1.0",
    "pandas>=2.2.3",
    "prettytable>=3.15.1",
    "pyperclip>=1.9.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "selenium>=4.30.0",
    "spotipy>=2.25.1",
    "twilio>=9.5.1",
    "undetected-chromedriver>=3.5.5",
]
